gantt
title 任务调度图
	dateFormat s
	axisFormat %S
	section CPU 1.1
	task2 :done, des1, 00, 03
	task6 :done, des1, 14, 24
	task8 :done, des1, 09, 11
	task10 :done, des1, 27, 29
	section CPU 1.2
	task9 :done, des1, 10, 17
	task11 :done, des1, 19, 28
	section CPU 2.1
	task1 :done, des1, 00, 04
	task4 :done, des1, 05, 10
	task7 :done, des1, 11, 14
	section CPU 2.2
	task3 :done, des1, 00, 04
	task5 :done, des1, 05, 08
	section BUS
	2->4 :done, des1,  3,  5
	2->5 :done, des1,  3,  5
	1->4 :done, des1,  4,  5
	3->5 :done, des1,  4,  5
	5->8 :done, des1,  8,  9
	5->9 :done, des1,  8, 10
	4->7 :done, des1, 10, 11
	8->11 :done, des1, 11, 12
	4->6 :done, des1, 10, 14
	7->10 :done, des1, 14, 15
	9->11 :done, des1, 17, 19
	6->10 :done, des1, 24, 27
